/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Embedded;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LongTran
 */
public class InforAccount extends javax.swing.JPanel {

    /**
     * Creates new form InforAccount
     */
    public InforAccount() {
        initComponents();
        Clear();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInfor = new javax.swing.JTable();
        btnChangeInfor = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnDeleteAcc = new javax.swing.JButton();

        setBackground(new java.awt.Color(193, 218, 193));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Information Account");

        btnSearch.setBackground(new java.awt.Color(255, 153, 0));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(238, 238, 238)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(btnSearch)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tblInfor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblInfor);

        btnChangeInfor.setBackground(new java.awt.Color(102, 0, 51));
        btnChangeInfor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChangeInfor.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeInfor.setText("Change Informatin");
        btnChangeInfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeInforActionPerformed(evt);
            }
        });

        btnChangePass.setBackground(new java.awt.Color(102, 0, 51));
        btnChangePass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePass.setText("Change Password");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        btnDeleteAcc.setBackground(new java.awt.Color(102, 0, 51));
        btnDeleteAcc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteAcc.setText("Delete Account");
        btnDeleteAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDeleteAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChangeInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnChangeInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static DefaultTableModel tableModel = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column)
        {
            return false;
        }
    };
    
     private Connection con = null;
    
    private void Clear(){
        int count = tblInfor.getRowCount();
        try{
        while (count > 0 ){
            tableModel.removeRow(0);
        }
        }catch(java.lang.ArrayIndexOutOfBoundsException e){
            e.getMessage();
        }
    }
    
    private void loadTable(){
         try {
            con = Connect.connect();
            
            Statement s = con.createStatement();
            
            
             
            ResultSet  rs = s.executeQuery("SELECT * FROM infomem");
            String []colsName = {"ID", "Username","Password","Full name","Address","Email","Gender","Day of birth"};
            tableModel.setColumnIdentifiers(colsName); 
            tblInfor.setModel(tableModel);
            while(rs.next()){ 
                Object rows[] = new Object[8];
                rows[0] = rs.getString(1);
                rows[1] = rs.getString(2);  
                rows[2] = rs.getString(3);
                rows[3] = rs.getString(4);
                rows[4] = rs.getString(5);
                rows[5] = rs.getString(6);
                rows[6] = rs.getString(7);
                rows[7] = rs.getString(8);
                tableModel.addRow(rows);
            }
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void Search(){
         try {
           con = Connect.connect();
            Statement s = con.createStatement();
            String Search = txtSearch.getText();
            String sql = "SELECT * FROM infomem where ID Like '%"+Search+"%' or Username Like '%"+Search+"%' or Fullname Like '%"+Search+"%'or Address like '%"+Search+"%' "
                    + "or Email Like '%"+Search+"%' or Gender Like '%"+Search+"%' or DOB Like '%"+Search+"%'";
            ResultSet rs = s.executeQuery(sql);
            while(rs.next()){ 
                Object rows[] = new Object[8];
                rows[0] = rs.getString(1);
                rows[1] = rs.getString(2);  
                rows[2] = rs.getString(3);
                rows[3] = rs.getString(4);
                rows[4] = rs.getString(5);
                rows[5] = rs.getString(6);
                rows[6] = rs.getString(7);
                rows[7] = rs.getString(8);
                tableModel.addRow(rows);
            }
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
     }
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    if(txtSearch.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Search not empty!");
       }else{
            Clear();
                    Search();
                    int Count = tblInfor.getRowCount();
                    if(Count == 0){
                        JOptionPane.showMessageDialog(null, "Don't search this database!");
                        Clear();
                    }else{
                        Clear();
                        Search();
                        JOptionPane.showMessageDialog(null, "Search seccess!");
                    }
       }
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private String Year(){
      
            int i = tblInfor.getSelectedRow();
            String DOB = (String) tableModel.getValueAt(i, 7);
            String Year = DOB.substring(0, 4);
        return Year;
    }
    
    private String Month(){
      
            int i = tblInfor.getSelectedRow();
            String DOB = (String) tableModel.getValueAt(i, 7);
            String Month = DOB.substring(5, 7);
        return Month;
    }
    
    private String Day(){
      
            int i = tblInfor.getSelectedRow();
            String DOB = (String) tableModel.getValueAt(i, 7);
            String Day = DOB.substring(8, 10);
        return Day;
    }
    
    
    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        Clear();
        loadTable();
        txtSearch.setText(null);
    }//GEN-LAST:event_txtSearchFocusGained

    private void btnChangeInforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeInforActionPerformed
        ChangeInfor ci = new ChangeInfor();
        
        int i = tblInfor.getSelectedRow();
        
        
        if(i > -1){
            int a = tblInfor.getSelectedRow();
            String ID = (String) tableModel.getValueAt(a, 0);
            String US = (String) tableModel.getValueAt(a, 1);
            String FN = (String) tableModel.getValueAt(a, 3);
            String Add = (String) tableModel.getValueAt(a, 4);
            String EM = (String) tableModel.getValueAt(a, 5);
            String Gen = (String) tableModel.getValueAt(a, 6);
            ci.setVisible(true);
            ci.cbbDay.setSelectedItem(Day());
            ci.cbbMonth.setSelectedItem(Month());
            ci.cbbYear.setSelectedItem(Year());
            ci.lbID.setText(ID);
            ci.lbUS.setText(US);
            ci.txtFN.setText(FN);
            ci.txtAdd.setText(Add);
            ci.txtEM.setText(EM);
            ci.cbbGen.setSelectedItem(Gen);
            ci.setRow(a);
        }else{
            JOptionPane.showMessageDialog(null, "You need select the row");
        }
    }//GEN-LAST:event_btnChangeInforActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        
        int i = tblInfor.getSelectedRow();
        
        if(i > -1){
            int a = tblInfor.getSelectedRow();
            ChangePass cp = new ChangePass();
            cp.setVisible(true);
            String ID = (String) tableModel.getValueAt(a, 0);
            String US = (String) tableModel.getValueAt(a, 1);
            cp.lbID.setText(ID);
            cp.txtUS.setText(US);
            cp.setRow(a);
        }else{
            JOptionPane.showMessageDialog(null, "You need select the row");
        }
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void DeleteAcc(){
        try {
            con = Connect.connect();
            Statement st = con.createStatement();
            int i = tblInfor.getSelectedRow();
            String ID = (String) tableModel.getValueAt(i, 0);
            String US = (String) tableModel.getValueAt(i, 1);
            
            String ifo = "Delete from infomem where ID ='"+ID+"' and Username = '"+US+"'";
            String acc = "Delete from account where ID ='"+ID+"' and Username = '"+US+"'";
            String rem = "Delete from remember where ID ='"+ID+"' and Username = '"+US+"'";
            st.executeUpdate(acc);
            st.executeUpdate(rem);
            st.executeUpdate(ifo);
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void btnDeleteAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccActionPerformed
       try {
           con = Connect.connect();
            Statement s = con.createStatement();
            int i = tblInfor.getSelectedRow();
            String ID = (String) tableModel.getValueAt(i, 0);
            String sql = "select * from `borrowde` where `IDUS` = '"+ID+"'";
            ResultSet rs = s.executeQuery(sql);
            if(!rs.next()){ 
                DeleteAcc();
                Clear();
                loadTable();
                JOptionPane.showMessageDialog(null, "Seccess!");
            }else{
                JOptionPane.showMessageDialog(null, "Connot delete this account!");
            }
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteAccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeInfor;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnDeleteAcc;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblInfor;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
